"""empty message

Revision ID: 48bc84a50a3c
Revises: 
Create Date: 2024-08-03 17:11:33.947653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bc84a50a3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('stockid', sa.String(length=64), nullable=False),
    sa.Column('agpd_value', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('number_of_trade', sa.Float(), nullable=True),
    sa.Column('w_buy', sa.Float(), nullable=True),
    sa.Column('w_sell', sa.Float(), nullable=True),
    sa.Column('day_last_update', sa.String(length=64), nullable=True),
    sa.Column('average_day', sa.Integer(), nullable=True),
    sa.Column('day_standard_deviation', sa.Float(), nullable=True),
    sa.Column('W_moderate_diff', sa.Float(), nullable=True),
    sa.Column('five_day_average', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('stockid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_agpd_value'), ['agpd_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_current_price'), ['current_price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_current_price'))
        batch_op.drop_index(batch_op.f('ix_user_agpd_value'))

    op.drop_table('user')
    # ### end Alembic commands ###
